services:
  postgres:
    image: postgres:17.2
    ports:
      - "${PG_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${PG_NAME:-postgres}
      POSTGRES_USER: ${PG_USER:-root}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-1234}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h postgres -p 5432" ]
      interval: 3s
      timeout: 3s
      retries: 10

  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "${SERVICE_PORT:-8080}:${SERVICE_PORT:-8080}"
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: ${PG_USER:-root}
      PG_PASSWORD: ${PG_PASSWORD:-1234}
      PG_NAME: ${PG_NAME:-postgres}
      PG_TIMEOUT: ${PG_TIMEOUT:-1s}
      PG_MAX_POOL: ${PG_MAX_POOL:-10}
      CONN_ATTEMPTS: ${CONN_ATTEMPTS:-10}
      SERVICE_HOST: ${SERVICE_HOST:-0.0.0.0}
      SERVICE_PORT: ${SERVICE_PORT:-8080}
      IS_TEST: ${IS_TEST:-false}

    depends_on:
      postgres:
        condition: service_healthy
